// P1 核收敛（计划 #71）：实现已上提到 `@base/protocol-ts`，本文件仅作显式 re-export 过渡，稳定后删除
export {
  ATTR_KIND_PREFIX,
  ATTR_ATTACHMENT,
  ATTR_BADGE,
  ATTR_BODY_MD,
  ATTR_CATEGORY,
  ATTR_COVER,
  ATTR_DIFFICULTY,
  ATTR_DURATION,
  ATTR_INSTRUCTOR,
  ATTR_TITLE_COLOR,
  DIFFICULTY_INTRO,
  DIFFICULTY_BASIC,
  DIFFICULTY_ADVANCED,
  DIGEST_KIND,
  DIFFICULTY_CHOICES,
  BADGE_WORDS,
  BADGE_WORDS_AUTHOR,
  TITLE_COLORS,
  serializeBadge,
  parseBadge,
  isTitleColor,
  isAttrKind,
  assignAttrSeqs,
  attrSeqsCanonical,
  segmentsContentHash,
} from '@base/protocol-ts';
export type { AttrLine, AttrSlot, SubmitSegmentRow } from '@base/protocol-ts';
